### ISSUE TITLE
plugin doesn’t work with kanban plugin - cannot paste links there

### ISSUE THREAD

**Issue by danieltomasz** [zolrath/obsidian-auto-link-title#11]
Great plugin, but recently I cannot paste link into kanban cards when autolink plugin is active
I already filled the issue there
https://github.com/mgmeyers/obsidian-kanban/issues/118

**Comment by zolrath** [comment]
Ah, I'll have to add a check to ensure that it's an obsidian editor! Thanks for the report!

**Comment by chrisgrieser** [comment]
I have noticed the very same thing – pasting links in a Kanban is not possible as long as the auto-title-plugin is enabled. [see the respective issue which I created there](https://github.com/mgmeyers/obsidian-kanban/issues/325).

**Comment by deathau** [comment]
I had a look into this issue because it was also happening with my CookLang plugin.
The issue is here: https://github.com/zolrath/obsidian-auto-link-title/blob/0b2c5b804dbfc6e3b32bbef8d5d0d6f77adec969/main.ts#L64
If this returns null (because it's not a markdown view and therefore has no editor) it still tries to use it in future checks (specifically `CheckIf.isMarkdownLinkAlready(editor)`) but because `editor` is null, those checks throw errors.

**Comment by zolrath** [comment]
I've hooked into the newish "editor-paste" event and no longer trigger any paste changes in search fields, nor does it have any effect in the Kanban plugin so you should be able to use Kanban normally as if this plugin were not enabled!

**Comment by pourmand1376** [comment]
I use a simple workaround for this problem until It is solved! 

First, I open a temporary note and paste my link there. Once auto-link-title has done its job, I simply paste it back to my kanban board.
