### ISSUE TITLE
Bad behaviour when I want past an url in the search field.

### ISSUE THREAD

**Issue by EKliptus** [zolrath/obsidian-auto-link-title#13]
For search purpose ( ctrl+f or ctrl+maj+f )
I need to be able to paste an url in the search box but when I paste the url, the editor capture the action and the url text is paste on the opened md document...
Thanks you for this good job !

**Comment by claremacrae** [comment]
Just to note that this is still happening in 1.2.3- I'd love to know if anyone finds a workaround other than turning the plugin off, as, so far as I can see, it makes it impossible to search for URLs in a vault.

**Comment by claremacrae** [comment]
This is still happening, and is quite a problematic issue. It feels like a keyboard problem, because you're looking at the search field, and typing the Paste short-cut - and nothing goes in to the search field.

So you paste a few more times - then give up...

And only then notice that you've messed your note by pasting in a load of unwanted text.

@zolrath Thank you for the very useful plugin - Could you give any pointers as to where to look, for how to fix this please, in case anyone has time to work on a PR?

**Comment by zolrath** [comment]
I've updated the minimum Obsidian version to 12.17 as it gives us access to the "editor-paste" event. Now that we only intercept pastes in the editor this issue should no longer occur!
