### ISSUE TITLE
YouTube link title not being fetched on mobile

### ISSUE THREAD

**Issue by sohanglal** [zolrath/obsidian-auto-link-title#46]
Instead of fetching the link title when pasting a link from YouTube.com it just shows YouTube on obsidian mobile.
For eg:
[YouTube](https://youtu.be/Q93ZF4D6mfc)
Instead of 
[The Problem with F1 Sponsorships - YouTube](https://youtu.be/Q93ZF4D6mfc)
This problem occurs for YouTube links on obsidian mobile on Android 10

**Comment by ZacharyVernec** [comment]
Same happens for Reddit links, e.g. 
[Reddit - Dive into anything](https://www.reddit.com/r/montreal/comments/wuv2jc/merci_montreal/)
rather than 
[Merci Montreal : montreal](https://www.reddit.com/r/montreal/comments/wuv2jc/merci_montreal/)

**Comment by sohanglal** [comment]
If I install the release 1.2.3 it is able to fetch the links properly on mobile.
@ZacharyVernec I suggest you install this version

**Comment by sohanglal** [comment]
Keeping this open in case anyone else has issues

**Comment by TrifarianGlory** [comment]
I'm still having this issue on Mobile Android Obsidian version 1.4.3, and auto link plugin version 1.4.1.
All reddit links appear as "Reddit - Dive into anything" instead of their title.

**Comment by garzonjav** [comment]
I am having the original issue when pasting a YouTube link using the iPhone Obsidian mobile application.
   
Example:
[YouTube](https://youtu.be/Q93ZF4D6mfc)
Instead of
[The Problem with F1 Sponsorships - YouTube](https://youtu.be/Q93ZF4D6mfc)

I am using:
Mobile Obsidian for iPhone ver 1.4.4
Auto Link plugin version 1.4.1 
iOS Version 16.3.1

**Comment by kazerniel** [comment]
I'm having issue with Reddit titles (on desktop), but only with the new scraper. I wonder if it's because it's faster than the old method? When I open a Reddit post in my browser, it does flash that "Reddit - Dive into anything" title for a moment before displaying the actual page title, but the plugin only captures that temporary one.

**Comment by hdlnii** [comment]
Issue still exists on mobile 2026-07
