### ISSUE TITLE
XSS - javascript execution when pasting certain links

### ISSUE THREAD

**Issue by kvn1338** [zolrath/obsidian-auto-link-title#81]
I am currently doing the PortSwigger XSS labs and taking notes in Obsidian. When I (carelessly) pasted my payloaded links into Obsidian I got an `alert` box. The alert did not trigger when I pasted the link with Shift+Ctrl+V, so it has to have been this Plugin.

This only happens when the lab is up and running, so you would have to start them to recreate it.

[Lab: Reflected XSS into a JavaScript string with single quote and backslash escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-string-single-quote-backslash-escaped)
I pasted the following link triggering an alert in Obsidian:
`https://[LAB-ID].web-security-academy.net/?search=AAAA%00\';%0A%0Aalert(1);//`

[Lab: Reflected XSS into a JavaScript string with angle brackets and double quotes HTML-encoded and single quotes escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-string-angle-brackets-double-quotes-encoded-single-quotes-escaped)
I pasted the following link triggering an alert in Obsidian:
`https://[LAB-ID].web-security-academy.net/?search=\\\%27;alert();//`

**Comment by kevNii** [comment]
Also works for this one: [Lab: Reflected XSS into a template literal with angle brackets, single, double quotes, backslash and backticks Unicode-escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-template-literal-angle-brackets-single-double-quotes-backslash-backticks-escaped)
with this link `https://[LAB-ID].web-security-academy.net/?search=AAAAAAAA${alert()}`

Seem a a lot of reflected XSS can trigger this? It's not all of them however; for [Lab: Reflected DOM XSS | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/dom-based/lab-dom-xss-reflected) the link `https://[LAB-ID].web-security-academy.net/?search=%5c%22%7d%3balert(1)%3b%2f%2f` works on the lab, but does not trigger an alert in Obsidian when fetching the title.

**Comment by kevNii** [comment]
Also works for this one: [Lab: Reflected XSS into a template literal with angle brackets, single, double quotes, backslash and backticks Unicode-escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-template-literal-angle-brackets-single-double-quotes-backslash-backticks-escaped)
with this link `https://[LAB-ID].web-security-academy.net/?search=AAAAAAAA${alert()}`

Seem a a lot of reflected XSS can trigger this? It's not all of them however; for [Lab: Reflected DOM XSS | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/dom-based/lab-dom-xss-reflected) the link `https://[LAB-ID].web-security-academy.net/?search=%5c%22%7d%3balert(1)%3b%2f%2f` works on the lab, but does not trigger an alert in Obsidian when fetching the title.

[closing issue was by accident]

**Comment by kevNii** [comment]
Also works for this one: [Lab: Reflected XSS into a template literal with angle brackets, single, double quotes, backslash and backticks Unicode-escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-template-literal-angle-brackets-single-double-quotes-backslash-backticks-escaped)
with this link `https://[LAB-ID].web-security-academy.net/?search=AAAAAAAA${alert()}`

Seem a a lot of reflected XSS can trigger this? It's not all of them however; for [Lab: Reflected DOM XSS | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/dom-based/lab-dom-xss-reflected) the link `https://[LAB-ID].web-security-academy.net/?search=%5c%22%7d%3balert(1)%3b%2f%2f` works on the lab, but does not trigger an alert in Obsidian when fetching the title.

[closing issue was by accident]

**Comment by kevNii** [comment]
Also works for this one: [Lab: Reflected XSS into a template literal with angle brackets, single, double quotes, backslash and backticks Unicode-escaped | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/contexts/lab-javascript-template-literal-angle-brackets-single-double-quotes-backslash-backticks-escaped)
with this link `https://[LAB-ID].web-security-academy.net/?search=AAAAAAAA${alert()}`

Seem a a lot of reflected XSS can trigger this? It's not all of them however; for [Lab: Reflected DOM XSS | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/dom-based/lab-dom-xss-reflected) the link `https://[LAB-ID].web-security-academy.net/?search=%5c%22%7d%3balert(1)%3b%2f%2f` works on the lab, but does not trigger an alert in Obsidian when fetching the title.

[closing issue was by accident]

**Comment by blueputty01** [comment]
This is a fantastic plugin and saves me a lot of time! 

@kevNii It looks like the plugin conditionally loads links in electron windows, so JS will always execute. This would solve issues of dynamic page titles (please correct me if I'm wrong). You could replace the conditional tt the bottom of `scraper.ts` with just the `nonElectronGetPageTitle` function if this is a concern. 

Although-- `nodeIntegration` is enabled and `webSecurity` is disabled in these windows, which seems it could be a security issue?

**Comment by kevNii** [comment]
@blueputty01 That does seem to be the issue.

What kind of saves this from being a RCE vulnerability is the introduction of [context isolation](https://www.electronjs.org/de/docs/latest/tutorial/context-isolation) in electron, which is enabled by default. Without this any website you paste would be able to use the node API and have full RCE on your machine.

However this is still an issue, since executing any website's JS is not what I expect when I paste a link. It still enables tracking users, leaking IPs, opening new browser windows,...

**Comment by ZhymabekRoman** [comment]
As a workaround, I can suggest implementing a backend server that parses the title tag from the body and nothing more. This may cause some site titles to be broken, but introducing headless options to parse web page titles can solve this problem. See #77

**Comment by pbhopeful** [comment]
@zolrath I'd like to ask you to reopen this one — the behaviour it describes is still present and unchanged in 1.5.5, which is the release it was closed alongside.

The close landed about fifteen minutes after 1.5.5 went out, and my guess is it got attributed to #128 (the LinkPreview API integration), which does implement the "parse the title server-side instead of rendering the page" idea suggested in this thread. But that path doesn't actually close the hole on a stock install:

- **It's opt-in and off by default.** `fetchUrlTitleViaLinkPreview` bails out unless `linkPreviewApiKey.length === 32`, and the default is `""` — so it returns `""` immediately for anyone who hasn't signed up for a key.
- **The caller treats `""` as a failure and explicitly falls through** — "Title via Link Preview failed, falling back to scraper" — into `getPageTitle`, which on desktop is still `electronGetPageTitle`, still `nodeIntegration: true` and `webSecurity: false`.

So with default settings the `BrowserWindow` path isn't merely still reachable, it's the *only* path. And even a user who does have a valid API key falls back into it whenever LinkPreview fails.

The reason I'm raising it rather than letting it lie: the consequence flagged in this thread back in 2023 — "it still enables tracking users, leaking IPs, opening new browser windows" — actually happened to me this week. A forced-redirect ad on an ordinary, legitimate site, rendered inside the hidden title-fetch window, opened three fake-antivirus tabs in my system browser with no interaction from me, and the leaked window went on executing until I fully quit Obsidian. Forensic writeup in #177.

I'm not asking for a particular fix in this thread — #177 has my suggestions, and there's a config-level mitigation (`useNewScraper`) that works today. Just that this stay open and findable, because right now anyone searching for whether Auto Link Title executes JavaScript from pasted links finds a closed issue marked completed and reasonably concludes it was handled.
