### ISSUE TITLE
Why does it take so long to fetch titles?

### ISSUE THREAD

**Issue by albertoloscerritos** [zolrath/obsidian-auto-link-title#87]
I'm using obsidian 1.4.14 and I feel this plugins (which I find very useful btw) takes too long to fetch the titles. Specially when compared with plugins like https://github.com/nekoshita/obsidian-auto-card-link or https://github.com/Meikul/obsidian-thumbnails which achieve a very similar (and more complex) task. 
The average time for me is between 1-3 seconds. I'm I doing something wrong?
Thanks.

**Comment by Atticuszz** [comment]
i encountered this problem as well ,also find that if move coursor in the title area ,it would be no response seems like blocking whole app by fetching title

**Comment by zolrath** [comment]
This should be improved with the newest version - if you're still seeing this please let me know and give example URLs/times!

**Comment by khaosdoctor** [comment]
@murazi @Atticuszz for what I could see, it depends a lot on three factors:

- How fast is the website in responding to the first byte of the request, since we don't need to whole page to load so we're able to get the link title
- How fast is the connection from your obsidian to the website (it seems that, on mobile devices, the TTFB is actually longer because it takes longer for the cellphone to connect to the website, so it's naturally slower)
- Obsidian seems to have an event or something in place that blocks everything else when you hover over links, so anything that try to change the text that's underneath the cursor is just discarded. I couldn't prove that this is a thing, but by observation it seems to have something in place

I the new version that's on #91 I tried to remove Electron from the play and rely solely on Obsidian's internal URL handler, which (hopefully) queues any event or anything that we need so it would bypass the 3rd point, however the other two are still valid and something we can't control. I tried to trim millis from everything I could find (including reducing the hash size, not 'computing' the hash but getting it from random bytes), please let us know if it's faster for you!

**Comment by Atticuszz** [comment]
thanks for your nice work！🥰it seems fixed now
